#=require foundation.min
#=
#=require underscore-min.js
#=require backbone-min.js
#=
#=require interact
#=require ./templates/templates
#=require_tree ./helpers
#=require_tree ./models
#=require_tree ./collections
#=require_tree ./views